apiVersion: v1
kind: Service
metadata:
  name: websrvc
spec:
  selector:
    server: web # This is the label that the deployment uses to select the pods
  type:  ClusterIP
  ports:
  - port:  8080
    targetPort:  80 # This is the port that the container listens on (containerPort)