apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-08-30T21:20:43Z"
  name: websrvc
  namespace: default
  resourceVersion: "4523"
  uid: b6e49f8c-e486-4f3c-8239-92d36a183121
spec:
  clusterIP: 10.109.25.28
  clusterIPs:
  - 10.109.25.28
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    server: web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
